version: '3.8'

services:
  rabbitMQ:
    image: rabbitmq:3.12-management
    container_name: rabbitMQ
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    restart: always
    networks:
      - simulacao-credito
    ports:
      - 5672:5672
      - 15672:15672

  keyclock:
    image: quay.io/keycloak/keycloak:23.0.4
    container_name: keyclock
    command: start-dev
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    restart: always
    networks:
      - simulacao-credito
    ports:
      - 8081:8080

  eureka-server:
    build: ./eureka-server
    ports:
      - 8761:8761
    container_name: eureka-server
    networks:
      - simulacao-credito

  ms-clientes:
    depends_on:
      - rabbitMQ
      - eureka-server
    build: ./ms-clientes
    container_name: ms-clientes
    networks:
      - simulacao-credito

  ms-cartoes:
    depends_on:
      - rabbitMQ
      - eureka-server
    build: ./ms-cartoes
    container_name: ms-cartoes
    networks:
      - simulacao-credito

  ms-avaliador-credito:
    depends_on:
      - eureka-server
    build: ./ms-avaliador-credito
    container_name: ms-avaliador-credito
    networks:
      - simulacao-credito


  ms-cloud-gateway:
    depends_on:
      - eureka-server
    build: ./ms-cloud-gateway
    ports:
      - 8080:8080
    container_name: ms-cloud-gateway
    networks:
      - simulacao-credito


networks:
  simulacao-credito:
    driver: bridge